=== Cophy08/spring-python/xml/schema/context/spring-python-context-1.0.xsd
<?xml version="1.0" encoding="UTF-8" standalone="no"?>

<xsd:schema xmlns="http://www.springframework.org/springpython/schema/components"
		xmlns:xsd="http://www.w3.org/2001/XMLSchema"
		targetNamespace="http://www.springframework.org/springpython/schema/components"
		elementFormDefault="qualified"
		attributeFormDefault="unqualified">

	<xsd:import namespace="http://www.w3.org/XML/1998/namespace"/>

	<xsd:annotation>
		<xsd:documentation><![CDATA[
	Spring Python XML Components Schema, version 1
	Authors: Greg Turnquist, Russ Miles

	This defines a simple and consistent way of creating a namespace
	of Spring Python components.
		]]></xsd:documentation>
	</xsd:annotation>
	
	<!-- base types -->
	<xsd:complexType name="identifiedType" abstract="true">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	The unique identifier for a component. The scope of the identifier
	is the enclosing component factory.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:attribute name="id" type="xsd:ID">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	The unique identifier for a component.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<!-- Top-level <components> tag -->
	<xsd:element name="components">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	The top level (typically root) element. Allows the definition
	of default values for all nested bean definitions.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:sequence>
				<xsd:element ref="description" minOccurs="0"/>
				<xsd:choice minOccurs="0" maxOccurs="unbounded">
					<xsd:element ref="component"/>
					<xsd:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
				</xsd:choice>
			</xsd:sequence>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="description">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	Contains informative text describing the purpose of the enclosing element.
	Used primarily for user documentation of XML component definition documents.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="0" maxOccurs="unbounded"/>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:group name="componentElements">
		<xsd:sequence>
			<xsd:element ref="description" minOccurs="0"/>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="property"/>
				<xsd:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:group>
	
	<xsd:attributeGroup name="componentAttributes">
		<xsd:attribute name="name" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	Can be used to create one or more aliases illegal in an (XML) id.
	Multiple aliases can be separated by any number of spaces, commas,
	or semi-colons (or indeed any mixture of the three).
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="class" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	The fully qualified name of the component's class.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="lazy-init" default="default" type="defaultable-boolean">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	Indicates whether or not this bean is to be lazily initialized.
	If false, it will be instantiated on startup by bean factories
	that perform eager initialization of singletons. The default is
	"false".

	Note: This attribute will not be inherited by child bean definitions.
	Hence, it needs to be specified per concrete bean definition.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="scope" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	The scope of this component: typically "singleton" (one shared instance,
	which will be returned by all calls to get_component with the given id), or
	"prototype" (independent instance resulting from each call to get_component).
	Default is "singleton".

	Singletons are most commonly used, and are ideal for multi-threaded
	service objects. Further scopes, such as "request" or "session", might
	be supported by extended factories (e.g. in a web environment).
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="local" type="xsd:IDREF">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	The name of the referenced local component. The value must be a component ID and thus can 
	be checked by the XML parser. This is therefore the preferred technique 
	for referencing components within the same factory XML file.
							]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:attributeGroup>
	
	<xsd:element name="component">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	Defines a single (usually named) component.

	A component definition may contain nested tags for constructor arguments,
	property values, lookup methods, and replaced methods. Mixing constructor
	injection and setter injection on the same bean is explicitly supported.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:extension base="identifiedType">
					<xsd:group ref="componentElements"/>
					<xsd:attributeGroup ref="componentAttributes"/>
				</xsd:extension>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="property" type="propertyType" >
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	Component definitions can have zero or more properties.
	Property elements correspond to setter methods exposed
	by the bean classes.
			]]></xsd:documentation>
		</xsd:annotation>
	</xsd:element>
	
	<xsd:complexType name="propertyType">
		<xsd:sequence>
			<xsd:element ref="description" minOccurs="0"/>
			<xsd:choice minOccurs="0" maxOccurs="1">
				<xsd:element ref="value"/>
				<xsd:element ref="ref"/>
				<xsd:element ref="list"/>
				<xsd:any namespace="##other" processContents="strict"/>
			</xsd:choice>
		</xsd:sequence>
		<xsd:attribute name="name" type="xsd:string" use="required">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	The name of the property.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="ref" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	A short-cut alternative to a nested "<ref component='...'/>".	
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="value" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	A short-cut alternative to a nested "<value>...</value>"
	element.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
		<xsd:attribute name="local" type="xsd:string">
			<xsd:annotation>
				<xsd:documentation><![CDATA[
	A reference to a locally declared component.
				]]></xsd:documentation>
			</xsd:annotation>
		</xsd:attribute>
	</xsd:complexType>
	
	<xsd:element name="value">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	Contains a string representation of a property value.
	The property may be a string, or may be converted to the required
	type using the JavaBeans PropertyEditor machinery. This makes it
	possible for application developers to write custom PropertyEditor
	implementations that can convert strings to arbitrary target objects.

	Note that this is recommended for simple objects only. Configure
	more complex objects by populating JavaBean properties with
	references to other beans.
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="0" maxOccurs="unbounded"/>
			<xsd:attribute name="type" type="xsd:string">
				<xsd:annotation>
					<xsd:documentation><![CDATA[
	The exact type that the value should be converted to. Only needed
	if the type of the target property or constructor argument is
	too generic: for example, in case of a collection element.
					]]></xsd:documentation>
				</xsd:annotation>
			</xsd:attribute>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="ref">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	Defines a reference to another component in this factory or an external
	factory (parent or included factory).	
			]]></xsd:documentation>
		</xsd:annotation>
		<xsd:complexType>
			<xsd:complexContent>
				<xsd:restriction base="xsd:anyType">
					<xsd:attribute name="component" type="xsd:string">
						<xsd:annotation>
							<xsd:documentation><![CDATA[
	The name of the referenced bean.
							]]></xsd:documentation>
						</xsd:annotation>
					</xsd:attribute>
					<xsd:attribute name="local" type="xsd:IDREF">
						<xsd:annotation>
							<xsd:documentation><![CDATA[
	The name of the referenced bean. The value must be a bean ID and thus can 
	be checked by the XML parser. This is therefore the preferred technique 
	for referencing beans within the same bean factory XML file.						
							]]></xsd:documentation>
						</xsd:annotation>
					</xsd:attribute>
				</xsd:restriction>
			</xsd:complexContent>
		</xsd:complexType>
	</xsd:element>
	
	<xsd:element name="null">
		<xsd:annotation>
			<xsd:documentation>
	Denotes a Python None value. Necessary because an empty "value" tag
	will resolve to an empty String, which will not be resolved to a
	None value unless a special PropertyEditor does so.		
			</xsd:documentation>
		</xsd:annotation>
		<xsd:complexType mixed="true">
			<xsd:choice minOccurs="0" maxOccurs="unbounded"/>
		</xsd:complexType>
	</xsd:element>
	
	<!-- Collection Elements -->
	<xsd:group name="collectionElements">
		<xsd:sequence>
			<xsd:choice minOccurs="0" maxOccurs="unbounded">
				<xsd:element ref="component"/>
				<xsd:element ref="ref"/>
				<xsd:element ref="value"/>
				<xsd:element ref="null"/>
				<xsd:element ref="list"/>
			<xsd:any namespace="##other" processContents="strict" minOccurs="0" maxOccurs="unbounded"/>
			</xsd:choice>
		</xsd:sequence>
	</xsd:group>
	
	<xsd:element name="list" type="listOrSetType">
		<xsd:annotation>
			<xsd:documentation><![CDATA[
	A list can contain multiple inner component, ref, collection, or value
	elements. The necessary conversion is automatically performed
	by the ComponentFactory.	
			]]></xsd:documentation>
		</xsd:annotation>
	</xsd:element>

	<!-- 'list' and 'set' collection type -->
	<xsd:complexType name="listOrSetType">
		<xsd:group ref="collectionElements"/>
	</xsd:complexType>
	
	<!-- simple internal types -->
	<xsd:simpleType name="defaultable-boolean">
		<xsd:restriction base="xsd:NMTOKEN">
			<xsd:enumeration value="default"/>
			<xsd:enumeration value="true"/>
			<xsd:enumeration value="false"/>
		</xsd:restriction>
	</xsd:simpleType>

</xsd:schema>

=== Cophy08/spring-python/docs/app-context-sample.xml
<?xml version="1.0" encoding="UTF-8"?>
<components xmlns="http://www.springframework.org/springpython/schema/components"
       xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
       xsi:schemaLocation="http://www.springframework.org/springpython/schema/components
       		http://springpython.webfactional.com/schema/context/spring-python-context-1.0.xsd">

	<description>
		This application context is used to show various components, defined using the
		code completion tools found in Eclipse, while pointed at an XSD spec.
		
		Please note that this sample is used to show pycontainer's format, which is supported
		by the XSD spec.
	</description>
	
	<description>You can have multiple descriptions at the root level.</description>

    <component id="user_details_service" class="springpython.security.userdetails.InMemoryUserDetailsService">
    	<description>
	    	This is an in-memory list of users, with their password and roles. It is valuable
	    	for unit testing without interacting with the real user authentication subsystem.
	    	
	    	The value between the property tags is run through a python evaluator, so it will
	    	translate the {...} text into a python dictionary with two entries.
    	</description>
	    <property name="user_dict">
			{
				"basicuser": ("password1", ["ROLE_BASIC"], True),
				"otheruser": ("password2", ["ROLE_OTHER"], True)
			}
        </property>
    </component>

    <component id="auth_provider" class="springpython.security.providers.dao.DaoAuthenticationProvider">
    	<description>This component has a property which references another component by name.</description>
	    <property name="user_details_service" local="user_details_service"/>
    </component>

	<component id="auth_manager" class="springpython.security.providers.AuthenticationManager">
		<description>
			This component has a property that holds a list of values, and in this case, is
			loading the list with references to other components.
		</description>
		<property name="auth_providers">
			<list local="auth_provider"/>
		</property>
	</component>
	
	<description>
		The following is a component with no properties.
		
		NOTE: This description is not tied to the RoleVoter component.
	</description>
	
	<component id="roleVoter" class="springpython.security.vote.RoleVoter"/>

	<component id="access_decision_mgr" class="springpython.security.vote.UnanimousBased">
		<description>
			This component has a mix of properties.
			
			The first property is evaluated as a python boolean False, NOT as a string of "False".
			
			The second property is a list, and will contain one entry, a reference to the roleVoter
			component.
		</description>
		<property name="allow_if_all_abstain">False</property>
		<property name="access_decision_voters">
			<list local="roleVoter"/>
		</property>
	</component>
	
	<component id="securityInteceptor" class="springpython.security.intercept.MethodSecurityInterceptor">
	  <property name="validate_config_attributes">False</property>
	  <property name="auth_manager" local="auth_manager"/>
	  <property name="access_decision_mgr" local="access_decision_mgr"/>
	  <property name="obj_def_source">
	    	[
				("springpythontest.support.testSecurityClasses.SampleService.get.*", ["ROLE_BASIC"]),
				("springpythontest.support.testSecurityClasses.SampleService.do.*", ["ROLE_BASIC"]),
				("springpythontest.support.testSecurityClasses.SampleService.update.*", ["ROLE_MGR"])
	      	]
	  </property>
	</component>

	<description>This is another stand alone component</description>	
	<component id="targetService" class="springpythontest.support.testSecurityClasses.SampleService"/>

	<component id="sampleService" class="springpython.aop.ProxyFactoryObject">
		<description>
			Hopefully by now you can deduce what this component's properties are made up of.
		</description>
		<property name="target" local="targetService"/>
		<property name="interceptors">
			<list local="securityInteceptor"/>
		</property>
	</component>
</components>
